### ISSUE TITLE
link generator does not work on ios

### ISSUE THREAD

**Issue by r10s** [deltachat/invite#14]
interestingly, the openpgp4fpr url has the protocol lowercased there, so `openpgp4fpr:` - where android/desktop have `OPENPGP4FPR` - and only the latter is removed by the invite-script.

i think, the invite-script should be tolerant here and support all case variations, in fact, the lowercase variant seems even "more correct", https://metacode.biz/openpgp/openpgp4fpr

**Comment by Simon-Laux** [comment]
desktop supports both variants (upper and lowercase):

https://github.com/deltachat/deltachat-desktop/blob/a7dfe4b07f3b3f8ed646316097ed69a2c2f974cc/src/main/open_url.ts#L14-L15

**Comment by r10s** [comment]
> maybe also try to make the upercase variant work in iOS too?

the issue is about creating the link, not about consuming them.

(when passing lowercase `opengpp4fpr` to i.delta.chat, you get a superfluous and wrong opengpp4fpr-string as outcome)
