### ISSUE TITLE
handle bad `#` character in `openpgp4fpr:` gracefully

### ISSUE THREAD

**Issue by r10s** [deltachat/invite#16]
there is still some encoding mess, the final opengpg4frp link does neither work on desktop nor on ios:

<img width="514" alt="Screenshot 2023-02-28 at 11 03 28" src="https://user-images.githubusercontent.com/9800740/221821477-ebef552f-0f5c-4f3c-97e0-b6102a939379.png">

there is a `#` encoded to `%23` that should not:

```
https://i.delta.chat/#341EA32E0D2FD84DC6DBE04BF03913F6BD0FFAD9%23a=bpetersen%40b44t.com&n=Bjoern&i=py4JSaMUDDa&s=NXeSd7VOoMC
```

lots of tiny thing with this hash-param-encoding, if we would do the protocol from scratch, we would probably done sth. easier, but we decided to build upon openpgp4frp at some point - and now we have to deal with that :)

**Comment by r10s** [comment]
hm, it is a bit more complicated, sometimes it works, needs more investigations ...

**Comment by r10s** [comment]
k, i think, i figured out the failing part:

- `getSecurejoinQr()` returns the correct string `OPENPGP4FPR:341EA32E0D2FD84DC6DBE04BF03913F6BD0FFAD9#a=...`
- with `UIPasteboard.general.string` copies the correct string correctly to the clipboard - pasting inside Delta Chat returns the correct string
- **but:** when pasting the string outside Delta Chat, ios seem to perform some magic and returns the string `OPENPGP4FPR:341EA32E0D2FD84DC6DBE04BF03913F6BD0FFAD9%23a=...` - for whatever reason. i tested that with Safari and Freeform. Notes returns the visible text correctly, the link is the wrong one.
- so, seems that accessing the clipboard as a URL changes things wrongly

i played around with using UIPasteboard.general.url for copying, without success so far.

i think, i.delta.chat should just convert the `%23` _directly after the fingerprint_ back to `#` (we should not just do a global replace)

**Comment by Simon-Laux** [comment]
maybe now is the time to reopen https://github.com/deltachat/deltachat-core-rust/issues/1969 and really also handle that case in core.
I'm not wondering too much in this case because there is already an anchor specified, safari might see the other `#` as a special character that needs to be uri encoded.

**Comment by r10s** [comment]
well, there is no other `#` in `openpgp4fpr:1234567890#param`.

but anyways, if core sees  the url as `openpgp4fpr:1234567890%23param` it should just use it in a tolerant way.

however, `i.delta.chat` should as well handle  `openpgp4fpr:1234567890%23param`  and not generate wrong links (again, be strict in what you write, tolerant in what you consume)

**Comment by rosano** [comment]
Would it be simple and safe to `decodeURIComponent`? In my Chrome console, both `decodeURIComponent('openpgp4fpr:1234567890%23param')` and `decodeURIComponent('openpgp4fpr:1234567890#param')` return `openpgp4fpr:1234567890#param`.

**Comment by r10s** [comment]
maybe, but that may decode too much, idk. iirc, it is about questionable interpretation of  of some url on mac, it is not that we are decoding completely wrong.

to not introduce other issues, i would fix the issue more on-point, using a regex hanfing exactly that case
