### ISSUE TITLE
register apps as handlers for https://i.delta.chat then document it

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/invite#19]
When apps register as handler for https://i.delta.chat then document it in https://github.com/deltachat/interface/blob/master/uri-schemes.md

**Comment by Simon-Laux** [comment]
We should do this (register for deep-linking in i.delta.chat on all platforms), especially since we are now switching the apps to output invite strings, it makes sense that when you have the app installed it does not open the webpage clicking on a link, instead going to the app immediately.

Also we can think about changing the qr code displayed in DC to an invite link as well in core, depending on how likely it is that people try to scan it without deltachat installed with their camera app.

**Comment by r10s** [comment]
initially, this issue was inly about documentation, however, as there are dedicater issues for the platforms, it seems fine to close it

otherwise, please to direct PR to target open points
